---
abstract: 'Merges two users into the same effective user'
author:
  - 'Alex Vandiver <alexmv@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-MergeUsers
no_index:
  directory:
    - html
    - inc
    - xt
  package:
    - RT::User
    - RT::Users
    - RT::Principal
requires:
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '1.00'
x_module_install_rtx_version: 0.34_03
x_requires_rt: 4.0.0
x_rt_too_new: 4.4.0
